/**
 * Central entry point: every public class and function of the package is re-exported from here.
 *
 * @packageDocumentation
 */
export { describeParameters, templateCatalog } from './catalog';
export type { ParameterInfo, ParameterKind, TemplateInfo } from './catalog';
export { deepMerge } from './core/object-fusion';
export { expandPath } from './core/params';
export { Texture } from './core/Texture';
export type { AnchorPoint, Corner } from './core/Texture';
export { hash, hashRange, hashSeed } from './core/hash';
export { circularDistance, clamp, firstPixel, mod } from './core/math';
export { createGradient, mixRGBA, sample, shade, shadeRGBA } from './core/palette';
export {
    ageParam,
    color,
    DETAIL,
    formatIssues,
    FROM_AGE,
    LAYOUT,
    palette,
    parseWith,
    range,
    ratio,
    shadowGroup,
    size,
    ValidationError,
} from './core/schema';
export {
    createMemoryLoader,
    loadPatch,
    patchDefinitionSchema,
    patchSize,
    placementAnchorSchema,
    placementSchema,
    renderPatch,
    renderTexture,
    renderTextureFile,
    textureDefinitionSchema,
} from './compose';
export type {
    Loader,
    PatchDefinition,
    Placement,
    PlacementAnchor,
    RenderTextureOptions,
    ResolvedPatch,
    TextureDefinition,
} from './compose';
export {
    generators,
    CATEGORIES,
    defineGenerator,
    ashlar,
    ashlarSchema,
    ashlarWear,
    banner,
    bannerSchema,
    bannerWear,
    bars,
    barsSchema,
    barsWear,
    beam,
    beamSchema,
    beamWear,
    bookshelf,
    bookshelfSchema,
    bookshelfWear,
    bricks,
    bricksSchema,
    cavewall,
    cavewallSchema,
    chain,
    chainSchema,
    chainWear,
    cobweb,
    cobwebSchema,
    cobwebWear,
    column,
    columnSchema,
    columnWear,
    door,
    dirt,
    dirtSchema,
    doorSchema,
    entablature,
    entablatureSchema,
    entablatureWear,
    fieldstone,
    fieldstoneSchema,
    fieldstoneWear,
    moss,
    glyph,
    glyphSchema,
    glyphWear,
    grass,
    grassSchema,
    grassWear,
    gravel,
    gravelSchema,
    metal,
    metalSchema,
    metalWear,
    mossSchema,
    opening,
    openingSchema,
    parchment,
    parchmentSchema,
    parchmentWear,
    planks,
    planksSchema,
    planksWear,
    sand,
    sandSchema,
    shield,
    shieldSchema,
    shieldWear,
    slot,
    slotSchema,
    slotWear,
    splatter,
    splatterSchema,
    stoneslab,
    stoneslabSchema,
    stoneslabWear,
    tapestry,
    tapestrySchema,
    glassWindow,
    windowSchema,
    windowWear,
    woodbeam,
    woodbeamSchema,
    woodbeamWear,
    computePlanksLayout,
    computeAshlarLayout,
    masonryShape,
    renderWall,
    WALL_ANCHORS,
    wallSchema,
} from './generators';
export type {
    AshlarBlock,
    AshlarParams,
    AshlarRow,
    AshlarWear,
    BannerParams,
    BannerWear,
    BarsParams,
    BarsWear,
    BeamParams,
    BeamWear,
    BookshelfParams,
    BookshelfWear,
    BaseParams,
    Category,
    BricksParams,
    CavewallParams,
    ChainParams,
    ChainWear,
    CobwebParams,
    CobwebWear,
    ColumnParams,
    ColumnWear,
    DirtTemplateParams,
    DoorParams,
    EntablatureParams,
    EntablatureWear,
    FieldstoneParams,
    GeneratorDefinition,
    GeneratorOptions,
    GlyphParams,
    GlyphWear,
    GrassParams,
    GrassWear,
    GravelParams,
    MetalParams,
    MetalWear,
    MossParams,
    OpeningParams,
    ParchmentParams,
    ParchmentWear,
    Plank,
    PlankColumn,
    PlanksParams,
    PlanksWear,
    SandParams,
    ShieldParams,
    ShieldWear,
    SlotParams,
    SlotWear,
    SplatterParams,
    StoneslabParams,
    TapestryParams,
    WindowParams,
    WindowWear,
    WoodbeamParams,
    ParamsSchema,
    RenderContext,
    TextureGenerator,
    WallDefaults,
} from './generators';
